name: Notion to Jekyll
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  notion-to-jekyll:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # 최신 버전으로 업데이트

      - name: Notion to Markdown
        # 이 부분이 변경되었습니다 (경로와 버전 수정)
        uses: ddelgu/notion-to-md-action@v1.0.1 
        with:
          notion_token: ${{ secrets.NOTION_TOKEN }}
          notion_database_id: ${{ secrets.NOTION_DATABASE_ID }}
          output_path: _posts

      - name: GitHub Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main